services:
  frontend:
    container_name: sveltekit
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/frontend
      - front_node_modules:/frontend/node_modules
      - front_svelte_kit:/frontend/.svelte-kit
      - front_build:/frontend/build
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
    depends_on:
      - backend

  backend:
    container_name: pocketbase
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
    volumes:
      - ./backend/pb_data:/backend/pb_data
    command: /backend/pocketbase serve --http=0.0.0.0:8090

volumes:
  front_node_modules:
  front_svelte_kit:
  front_build: